// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYcLjmEawnBZdaeV2kNOLLrEaExkP_j8g',
    appId: '1:287638238391:web:b03cb9b74f1267b4d14932',
    messagingSenderId: '287638238391',
    projectId: 'crisisai-730dc',
    authDomain: 'crisisai-730dc.firebaseapp.com',
    storageBucket: 'crisisai-730dc.firebasestorage.app',
    measurementId: 'G-HHMYVLGP1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3CCj84gDc0xTVQ20hGfMk1CsP_UE2Csc',
    appId: '1:287638238391:android:9dcf87ca7c976d27d14932',
    messagingSenderId: '287638238391',
    projectId: 'crisisai-730dc',
    storageBucket: 'crisisai-730dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCypGRe1FxLfUViPXWRozIs_3Jzdh5l2AI',
    appId: '1:287638238391:ios:0f735e99f849bc80d14932',
    messagingSenderId: '287638238391',
    projectId: 'crisisai-730dc',
    storageBucket: 'crisisai-730dc.firebasestorage.app',
    iosBundleId: 'com.example.crisisAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCypGRe1FxLfUViPXWRozIs_3Jzdh5l2AI',
    appId: '1:287638238391:ios:0f735e99f849bc80d14932',
    messagingSenderId: '287638238391',
    projectId: 'crisisai-730dc',
    storageBucket: 'crisisai-730dc.firebasestorage.app',
    iosBundleId: 'com.example.crisisAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYcLjmEawnBZdaeV2kNOLLrEaExkP_j8g',
    appId: '1:287638238391:web:d3973b5d7698ae39d14932',
    messagingSenderId: '287638238391',
    projectId: 'crisisai-730dc',
    authDomain: 'crisisai-730dc.firebaseapp.com',
    storageBucket: 'crisisai-730dc.firebasestorage.app',
    measurementId: 'G-9Y0LXKNRJ3',
  );
}
